### ISSUE TITLE
 Automatic Hint Reflection

### ISSUE THREAD

**Issue by dmos62** [mathesar-foundation/mathesar#1038]
## Problem
We’re currently working on a hint system that would allow us to assign useful information to functions and types. Currently, the hints are compiled by-hand, which could become cumbersome if the number of functions or types exploded. Also, user developers might find the hint system a barrier to using their own functions or types (though we're working to minimize that). 

## Proposed solution
We’ve discussed the possibility to reflect function properties automatically, which would allow us to also assign (at least some) hints to functions automatically. The automatic reflection is not essential, but it could be a significant quality-of-life improvement. Its implementation seems too expensive for the core team to take up in the near term. At the same time, it’s fairly isolated from the rest of Mathesar, which is good for new contributors.

Here's an outline for getting automatic reflections off the ground, as I see it:

- Research what is the intersection between the things that would be useful for Mathesar to automatically reflect and what can be automatically reflected;
- Create an accurate picture of what cases the automatic reflection will fully cover and in what cases information (hints) will have to be overridden or supplemented manually;
- Figure out when to reflect and how to cache the reflections so as to minimally burden the wider system with more state;
- Do the implementation.

## Additional context
This has been submitted as a GSOC project idea: https://wiki.mathesar.org/en/community/mentoring/project-ideas#automatic-hint-reflection

**Comment by mathemancer** [comment]
Function signatures (including output type) can be easily(ish) reflected for any DB function that I'm aware of (including infix operators).  Irritatingly, infix operators are implemented under the hood as non-overloaded prefix-notation functions, so sorting out the overlap there might prove a bit tedious (since the operators are overloaded and point to multiple prefix-notation functions).  The signature is just the beginning.  To see what can be reflected about functions, explore the `pg_proc` system table, the `pg_operator` system table, and the `pg_catalog.pg_get_...` functions (e.g., `pg_get_function_arguments`, `pg_get_function_result`, etc.).  Also check out the `pg_catalog.obj_description` function for getting "human friendly" descriptions of objects (including but not limited to functions and operators).

Also, @dmos62 do you think the framework you've set up is appropriate only for "normal" functions, or also aggregations and window functions?  I can't think of any big problems with that, but it would be worth knowing any issues that might arise.  (We can also reflect that nature of a function, e.g., whether it's a "function" or "aggregation" or "window aggregation".

For types, we can also reflect lots of relevant information using many of the concepts above, but with different system tables as the data sources.

Overall, I'm having trouble thinking of info that we'd want in hints, but _can't_ reflect.  Given that, I'm starting to think that we should consider reflecting as the default, and adding hand-curated info only when crucial.

**Comment by kgodey** [comment]
This issue is meant to be a GSoC project, let's defer further work until someone shows interest.

**Comment by aditmehta9** [comment]
@kgodey @dmos62 @mathemancer I really want to work on this project and I have been trying to understand this issue. For the past couple of days, I have been reading and trying to understand different files but I'm not getting it. Can you please guide how should I start or what things to understand before I dive into this issue? It would be really helpful.

**Comment by kgodey** [comment]
@aditmehta9 This issue is marked `draft`, which means that it doesn't have enough details to get started on yet. It's intended to be fleshed out during the GSoC project. We have a [very detailed project description](https://wiki.mathesar.org/en/community/mentoring/project-ideas/automatic-hint-reflection) that provides more details about the general problem.

As @mathemancer pointed out, it's best to contribute to a couple of smaller issues first so that you can get used to the codebase.

**Comment by mathemancer** [comment]
As we move to an RPC API, it's likely this won't be relevant. I'm going to close it, but may steal bits of this issue for another once the new endpoint is being implemented.
