### ISSUE TITLE
Add new docker service for integration tests

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#1044]
## Problem
#639 Introduces integration testing environment which brings a new `DockerFile` and uses a different Linux image, which takes time to build. Moreover having to switch between different `Dockerfile` makes development harder.
## Proposed solution
Use a different docker service for integration tests.

## Additional context
- Discussion on https://github.com/centerofci/mathesar/pull/746

**Comment by kgodey** [comment]
I updated the issue with a link to the (long) discussion we had on this topic in the E2E setup PR. Whoever is working on this should read through that thread because @pavish tried a lot of different things before settling on this setup.

**Comment by seancolsen** [comment]
> Moreover having to switch between different Dockerfile makes development harder.

Yes. I want to reiterate this point and elaborate a bit in case others are not seeing the difficulty here. 

I've been toggling between different git branches as I work on different tickets. I've frequently had to run `docker-compose up --build`. Because I'm using the E2E Dockerfile, every time I need to build, I need to:

1. edit `docker-compose.yml`
2. `sudo rm -rf .volumes/`(Wiping away the sample data I've been working with.)
3. `docker-compose up --build` (takes ~5 minutes)
4. `docker exec mathesar_service python manage.py migrate`
5. `docker exec -it mathesar_service python install.py`
4. undo my edits to `docker-compose.yml` so they don't get committed
5. Re-add my sample data to Mathesar.

I've probably done this dance 1/2-dozen times in the past few working days. Getting accustomed to this workflow was a bumpy process too, since I'm still a Docker novice. Perhaps it's just a coincidence that I'm working within different branches right now that make changes to the container though.

**Comment by kgodey** [comment]
Integration tests are currently disabled, closing.
