### ISSUE TITLE
Improve column type inference

### ISSUE THREAD

**Issue by dmos62** [mathesar-foundation/mathesar#2346]
## Problem
Superseded issue: https://github.com/centerofci/mathesar/issues/2250

At the moment importing tables from CSV files doesn't work as well as it could, especially when importing tables that take a long time to have their column types inferred. This meta task is about making column type inference a non-problem when importing tables. See discussion in superseded issue for more context.

> I think the problems are the following:
>
> - column type inference is probably inefficient;
> - ~~we're not handling timeouts;~~
> - we're trying to fit column type inference into a HTTP transaction; that's not smart, because the duration of this task depends on input outside our control;
> - infering column types is an uninterruptable, monolithic operation for which you don't see incremental progress; there's no reason why we couldn't do it per-column;
> - column type inference is obligatory.

## Proposed solution

- [x] #2358
- [ ] #2359
- [ ] #2360
- [ ] #2347

**Comment by shrey27tri01** [comment]
I researched a bit on how to improve inference performance on wide tables, with a large number of columns; one of the articles I found was [this](https://itnext.io/building-a-schema-inference-data-pipeline-for-large-csv-files-7a45d41ad4df) one, which mentions about a pipeline using a few methods to improve inference performance. The author performed the below steps to get a considerable improvement in inference time:

1. Using [mmap](https://docs.python.org/3/library/mmap.html) for an improved I/O performance, since _mmap_ uses memory-mapped file IO
2. Uniform distribution of the records into chunks to  parallelize the inference process (based on rows)
3. Join the different results to get a single schema

Although the program was originally intended for tables with a large number of rows and not columns, the 1st and 2nd steps can still be used for the problem at hand. 

There is also an open [issue](https://github.com/pandas-dev/pandas/issues/9969) in the Pandas repository regarding poor read performance on wide CSV files, and one of the techniques mentioned there was to transpose the original CSV (although I'm not sure how this could be implemented, or even work in this case). 

These methods are, of course, apart from what @dmos62 has already mentioned, and can be looked into to optimize column type inference. I would be happy to take up any of these tasks, or the ones that have already been created. Specifically, I was interested in #2373 (making type-casting SQL functions parallelizable using inline functions).

**Comment by dmos62** [comment]
@shrey27tri01 glad that you're interested. Note that we use Postgres to do the heavylifting and we're thinking of moving more of the related logic into Postgres at some point, while the article you linked talks about doing that in Python, so we'll likely not be interested in that. Your listed ideas about parallelizing parts of the workload are actually something we've discussed. For one reason or another we've not put them in the backlog, probably because we didn't expect the improvements they'd provide to be attractive relative to other options. These techniques are something we might experiment with once we've moved the inference logic into Postgres, but by then the inference performance might already be good enough, so who knows.

Note, I'd say only #2371 and #2373 (out of the related issues) are currently open to non-core-team contributors. If you're thinking of applying for GSOC with us, I encourage you to continue coordinating on our Matrix in the public channels.

**Comment by shrey27tri01** [comment]
Sure, the ideas given were just out of interest in the issue at hand. I will try to understand the issues you mentioned (#2371 and #2373) and work on one of them. Thanks a lot for the information!

**Comment by dmos62** [comment]
@shrey27tri01 by the way, #2373 is [earmarked for GSOC](https://wiki.mathesar.org/en/community/mentoring/project-ideas/make-casting-functions-inlinable), so unless you're applying for that GSOC project, it would be a good idea to wait until we know that the associated GSOC project is not happening.

**Comment by shrey27tri01** [comment]
Okay, that makes sense. I'll wait till that time. Thanks for letting me know!

**Comment by kgodey** [comment]
Closing, I don't think we need a meta-issue for this.
