### ISSUE TITLE
Set up load balancer and additional servers in GCP

### ISSUE THREAD

**Issue by kgodey** [mathesar-foundation/mathesar#2543]
This issue involves:
- [x] Set up a load balancer in GCP (ensure it supports sticky sessions)
- [x] Create demo server template based on existing demo server
- [x] Have the load balancer create new images automatically based on demo server template
- [x] Connect the existing demo server to it.
- [ ] Document the process to update the demo server template and make load balancer use the new template

**Comment by dmos62** [comment]
Here's an idea. Judging by how many user demo databases a given demo server instance has, we could infer that it might need a certain number of connections (e.g. ~3 per database). We would also know that a given server can have some maximum of connections (e.g. ~200). That means that we can decide whether or not a given demo server is ready to accept a new user (a new database, in other words), by calculating something like `current_db_count * 3 < 200`. If we tune these variables right, we should end up with demo servers that are very unlikely to crash due to hitting the connection limit.

Aggressively cleaning up unused dbs (logging out inactive users) might be desirable to maximize server utilisation.

Not sure how easy this is to implement though. @silentninja what do you think?

**Comment by silentninja** [comment]
Loadbalanced live-demo server is up at https://mathesar.dev/

**Comment by kgodey** [comment]
Everything except the documentation is done here, and the documentation is now tracked in Basecamp [here](https://3.basecamp.com/5718119/buckets/35368592/todos/6866366239).
