### ISSUE TITLE
Support for delimiter type when importing tables

### ISSUE THREAD

**Issue by ricnov** [mathesar-foundation/mathesar#2921]
When importing a new file for a new table it could be good to have the possibility to choose the delimiter to parse the data

**Comment by rajatvijay** [comment]
@ricnov I am curious what other delimiter are you using?

**Comment by ricnov** [comment]
@rajatvijay semicolon and pipe, but it could be anything actually

**Comment by Aritra8438** [comment]
> @rajatvijay semicolon and pipe, but it could be anything actually

Hi @ricnov, refer to [this]( https://github.com/centerofci/mathesar/issues/2753) issue. Currently, Mathesar supports `;` and `|` as delimiters.

**Comment by ricnov** [comment]
Hi @rajatvijay It doesn't work with semicolon (latest version updated)

**Comment by kgodey** [comment]
@Aritra8438 we haven't done a release with that fix yet. 

@ricnov we'll be releasing a new version of Mathesar soon that adds support for semicolons n the next week or two.

**Comment by dmos62** [comment]
@ricnov this issue [should be fixed](https://github.com/centerofci/mathesar/blob/c9197b9a68c36b63e47e7d87ece59ee63b358cff/mathesar/imports/csv.py#L19) in the last release (0.1.2).

Would you be interested in verifying that your reported problem is indeed fixed?

If not, we'll close this issue in 2 weeks.

**Comment by seancolsen** [comment]
@ricnov

The maintainers team met today to discuss this issue. We are closing this because it seems likely enough that your problem was addressed when we added support for semicolon delimiters in #2759.

You said:

> it could be good to have the possibility to choose the delimiter

and

> semicolon and pipe, but it could be anything actually

I want to recognize that we've _not_ added support for arbitrary, user-defined delimiters, which seems to be part of your original request. Nonetheless, we're closing this issue for the purpose of focusing our efforts and priorities on the most important features that will get Mathesar to a beta release. If user-defined delimiters is important to you, then feel free to open a new ticket or comment here explaining more about your use case so we can understand the problem better. We can re-open this ticket and re-scope it if needed.
