### ISSUE TITLE
Column endpoint is slow when columns are many

### ISSUE THREAD

**Issue by dmos62** [mathesar-foundation/mathesar#3135]
## Problem
The column endpoint seems exceptionally slow when the associated table has many columns. On my machine, on a table with 100 columns (and ~500 rows), the column endpoint takes ~12 seconds to respond.

Attaching [small-long.csv](https://github.com/centerofci/mathesar/files/12293080/small-long.csv) which I used to reproduce (100 columns and ~500 rows).

## Proposed solution
Improve performance of the columns endpoint: make it less sensitive to column count.

**Comment by gulianow** [comment]
Hi, I would like to contribute on this project. Can you assign me on this issue?

**Comment by dikwickley** [comment]
This issue is still there. When I tried to import this in local env it took `~22 secs`
<img width="1525" alt="image" src="https://github.com/centerofci/mathesar/assets/31622972/d2ac92a8-e327-405d-a897-c95ee26f2994">

and causing a gateway timeout `>30 secs` on mathesar demo 
<img width="1525" alt="image" src="https://github.com/centerofci/mathesar/assets/31622972/b4d15594-0398-4cf9-b18c-5cde886430c0">

@seancolsen if this optimization is still required, i would like to take a stab at it.

**Comment by seancolsen** [comment]
@dikwickley yes, this performance issue is absolutely still a problem, and fixing it is a high priority for us. However, I have a hunch that this ticket might not be appropriate for someone without an intimate understanding of our backend architecture and the upcoming changes we have in-mind for it.

I'm going to ask one of our backend engineers to weigh in...

@mathemancer Can you comment on this ticket and answer these questions:

- Is this ticket appropriate for newcomers? If so, can you give a comment pointing implementers in the right direction? If not, can you please apply the `restricted: maintainers` label here?

    (For some context, @dikwickley is a new contributor who has made [a couple useful PRs](https://github.com/centerofci/mathesar/pulls?q=is%3Apr+author%3Adikwickley+) already. Those PRs have been small front end changes, but @dikwickley has demonstrated keen attention to detail and g]good communication.)

**Comment by Anish9901** [comment]
This is a major perf bottleneck and would require a full backend architectural redesign. Hence not a good place to start for a newcommer.

Some context: the `columns/` endpoint and the `tables/` endpoint as a whole is what is slowing our app down this is due multiple back and forth communication b/w the backend and the database that is required to reflect the information to client. Currently these endpoints request a lot of data which ends up openning up a lot of connections to the database. Going forward we might look into providing contextual data to the user instead of having a to query up a lot of stuff from the database hence reducing latency.

**Comment by seancolsen** [comment]
This should be fixed now
