### ISSUE TITLE
Add a Github action to build static files and add it as a asset to the release page

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#3163]
## Problem
We will be building various packages like a `.deb` file during release which will be used for installing Mathesar. These packages need compiled static assets along with the source code. To be consistent we need to maintain a single source of truth for the source which will be used for various packages.

## Proposed solution
When we make a release, we can make use of GitHub actions to build the static files from the release branch, zip them along with other source code files, and add them to the release assets.
![github com_centerofci_mathesar_releases_tag_0 1 2](https://github.com/centerofci/mathesar/assets/4469754/dc667a5a-abae-4ba1-9725-f52bdb76942f)

**Comment by silentninja** [comment]
> @silentninja If possible, I would make the assets _part_ of the "Source code" asset rather than a separate asset.

The "Source code" archives are generated using [git-archive](https://git-scm.com/docs/git-archive) which [cannot be modified](https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/) as they are generated dynamically directly from the git release branch. 

We can instead have our own minified zip which excludes irrelevant files like docs and instead contains only source code-related files

**Comment by seancolsen** [comment]
We discussed this during a maintainers team meeting today. We're closing because we don't need to do this anymore.

For our Docker Compose installation method we don't need this because node is included within the Docker image. We could theoretically make the docker image smaller if we did this. We might want to do this at some point in the future. We can revisit at that point if needed.
