### ISSUE TITLE
Deprecate Build from scratch documentation

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar#3169]
Based on our [installation plan](https://wiki.mathesar.org/en/projects/installation-improvements-plan-0_1_4), we won't be supporting Install from scratch as a recommended installation method. 

The following guides need to be marked as deprecated
- [Build from scratch](https://docs.mathesar.org/installation/build-from-source/) 
- The [Build from scratch](https://docs.mathesar.org/installation/guided-install/) should point to the Debian install documentation added by #3165 for users who have already installed Mathesar using the "Build from scratch" instructions

**Comment by kgodey** [comment]
Attn: @mathemancer @Anish9901 @seancolsen 

I brought up in the weekly meeting today that this needed more discussion. This was originally specced out with the assumption that the Debian package install was going to replace the current "build from scratch" documentation, since we do want to support at least one method of installing Mathesar without Docker.

Since we have cut the Debian package from this release, I don't think we should deprecate this for 0.1.4 (or basically until we have another method of installing Mathesar without Docker).

**Comment by seancolsen** [comment]
Addressed in #3227
