### ISSUE TITLE
Persist Data Explorer State through CTRL+R

### ISSUE THREAD

**Issue by mathemancer** [mathesar-foundation/mathesar#3181]
## Problem

While working on a QA task, I unthinkingly pressed `CTRL+R` to reload a page in Data Explorer. I'd added a few columns, and started to build up a query there. To my surprise, all of the state associated with that query was (without warning) immediately deleted.

## Proposed solution

I think we should consider figuring out some way to persist the state associated with a data explorer 'session' (term used loosely). I.e., If I press `CTRL+R` to see the current 'query', but with refreshed data (or to see the sent request in devtools), the resulting page should look more-or-less the same way I left it.

## Additional context

I was actually trying to resend a request to see its form and hadn't paid enough attention. I think the actual danger to a general user here is "I want to refresh the underlying data", which is a desire I can easily imagine them trying to fulfill by pressing `CTRL+R` without thinking. I bet they'd even make that mistake multiple times before being properly trained.

For context, pressing `CTRL+R` from this page in data explorer:
![image](https://github.com/centerofci/mathesar/assets/6829750/50bdd880-71b1-45b3-b532-ce1cc31327ea)
results in this page:
![image](https://github.com/centerofci/mathesar/assets/6829750/4efd8eea-7982-4368-8d56-50698d6f7f24)

It's not possible to recover the first state (i.e., the page with the columns chosen, etc. once you've done this.

**Comment by mathemancer** [comment]
Leaving as "Draft" and "Triage" while we figure out if we want to do this, and how.

**Comment by seancolsen** [comment]
@pavish [said](https://matrix.to/#/!UnujZDUxGuMrYdvgTU:matrix.mathesar.org/$IRtpoaYTBqC8xF5ba6e56k7v0FTGY9uVajqOf5EQ6wY?via=matrix.mathesar.org&via=matrix.org):

> Yeah, we serialize the filters, grouping, sort etc., and make it as params in the url for tables. For queries, serializing the object produces a super large url, so I didn’t handle it. We would have to store it using a different mechanism.. probably in the local storage.

If we use localStorage, we'll need to consider the behavior of a user with two unsaved Data Explorer tabs open at the same time. This gets a bit tricky. I'd be curious to hear your ideas for addressing this, @pavish.

- One approach would be **"last write wins"** where the Data Explorer saves its query to _one_ location within localStorage each time the user mutates the query. However, this gets tricky if the user modifies a query in tab A and then refreshes a query in tab B.

- Another approach would be **"keyed caches"** where the Data Explorer creates a unique key for each query and saves values to localStorage associated with the key. With this approach, we'd need to figure out a way to purge stale data periodically, so we'd also need to store a last-access timestamp with each saved value.

In general, I really like the pattern of saving data in the URL. I share the concern about having URLs that are too long, but I'd be interested in exploring it a bit further before ruling it out. For example, I wonder how long it would be with _compression_ + base64 encoding.

As a side note, this problem is one of the many reasons why I'm excited about the idea designing the Data Explorer around a user-friendly _query language_ &mdash; because serializing _that_ into a URL actually _would_ be relatively concise.

**Comment by pavish** [comment]
I was thinking of the keyed caches approach when I suggested local storage. The key would be part of the url. We would have to figure out purging stale state but I don't think it'd be challenging.

Another option would be to use the same keyed cache approach but store it on the backend. The client will make a keep-alive request periodically while the explorer is open, and the backend can purge it if a keep-alive request hasn't been received in a while.

> I share the concern about having URLs that are too long, but I'd be interested in exploring it a bit further before ruling it out. For example, I wonder how long it would be with compression + base64 encoding.

We can explore it, but I _think_ it'd be quite long, I already share that concern with our table urls which get very long when we add enough filters. As we have more options to customize/filter explorations and tables, this would keep increasing, and we'd also be forced to make sure updates are backwards compatible since urls can be shared.

I'd very much prefer the approach I suggested above where we persist these customizations on the backend and use a unique url for it. A lot of products (I'm sure airtable does) use similar approaches.

---

Regarding the problem here, I think a better solution might be to show an alert to the user that unsaved changes will be lost when they move away from the page (or refreshed). I remember the initial design having it. However, I think this would require us to make changes to the router (or having to build our own), in addition to making use of the `beforeunload` event.

This issue should also include figuring out the best UX before working on a solution.

**Comment by seancolsen** [comment]
> show an alert to the user that unsaved changes will be lost when they move away from the page

Good idea!

**Comment by seancolsen** [comment]
The maintainers team met today to review this issue and we decided not to close this issue because we are in the midst of re-thinking the Data Explorer more holistically. We will take this use case into consideration as we plan the direction we'd like to head with the Data Explorer.
