### ISSUE TITLE
Improve failure scenario when attempting to create a connection with invalid credentials

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#3383]
## Current behavior

- When creating new connections, Mathesar saves the connection even if it can't connect to it.
- This is a problem because it's possible to save a connection that could later become valid. In that case, the database won't have our schemas installed.

## Desired behavior

- We'd like to fix this by failing to save the connection if we can't connect to it.

We discussed this at a maintainers meeting today and decided to _try_ getting this into the v0.1.4 release. We can move to a later milestone if it becomes too much work.

**Comment by Anish9901** [comment]
@seancolsen @mathemancer, do we want to error check the connection strings added via `MATHESAR_DATABASES`  before storing?

**Comment by seancolsen** [comment]
@Anish9901 I think "no" because (if I understand correctly) `MATHESAR_DATABASES` will only be used for our test suite from this point forward.

**Comment by Anish9901** [comment]
@seancolsen, In #3388, I've made it so that when invalid credentials are added to `MATHESAR_DATABASES` the app generates an error that can be seen in the logs, and those credentials aren't stored in the internal db. My rationale behind making it this way is that:
- someone upgrading mathesar will already have their credentials configured via `MATHESAR_DATABASES` and by taking this approach we only store connection(s) that aren't stale(in case there are multiple connections).
- even if we _did_ store those stale connections and those credentials do become valid sometime in the future, for Mathesar the connection would still remain stale as we don't attempt to install our schemas on dbs of already stored connections.

**Comment by seancolsen** [comment]
Ok cool. I'll defer to whatever decision you and @mathemancer agree upon.
