### ISSUE TITLE
Windows line endings error when attempting to set up development environment

### ISSUE THREAD

**Issue by MayaSatishRao** [mathesar-foundation/mathesar#3385]
## Description
I followed the instructions to set up Mathesar on my device and I encountered this error. I used Docker on Windows 11 machine.
`/usr/bin/env: ‘bash\r’: No such file or directory`

## Expected behavior
Installation should be successful

## To Reproduce
Follow steps to install in a Windows machine.

## Environment
 - OS: Windows 11

## Solution
I found out that in Windows we need to chang line feed from CRLF to LF. We can do that by adding 
`--config core.autocrlf=input`
 to git clone command and it resolved the issue in my case. We need to add this to the documentation.

**Comment by MayaSatishRao** [comment]
@seancolsen can you look into this?

**Comment by seancolsen** [comment]
@MayaSatishRao to be clear: you are following our [Developer Guide](https://github.com/mathesar-foundation/mathesar/blob/develop/DEVELOPER_GUIDE.md) to set up a Mathesar development environment, right? _Not_ following our [installation documentation](https://docs.mathesar.org/) to install Mathesar, right?

The problem you seem to be experiencing is a very common problem for Mathesar devs on Windows. Ironing out this kink has been a challenge for us, in part because none of our maintainers use Windows.

Did you follow the _"If you are developing on Windows"_ instructions which specify that you should run `git clone` from within WSL?

We are certainly open to PRs which improve the docs in order to help other devs avoid this pitfall. Please feel free to submit a PR and we can discuss your proposed changes there.

**Comment by MayaSatishRao** [comment]
@seancolsen I followed developer guide but I ran the commands in Terminal of VS Code.

**Comment by seancolsen** [comment]
If you choose not to use WSL at all, then I have a hunch you'll be in for more problems than just this. Maybe not. But it's just that we only maintain dev docs for Windows devs who _are_ using WSL, so I suspect there are other problems lurking in our development workflow that nobody has yet bumped into because (as far as I know) all the Mathesar devs on Windows have done their work from within WSL.

I don't think we would be open to PRs against our dev docs which attempt to support Windows-based development workflow outside of WSL at the moment. We could discuss this if you feel strongly about continuing development outside of WSL. But personally I'm inclined to mandate WSL for the sake of operational simplicity. It just feels like opening a can of worms otherwise, and we have bigger priorities at the moment.

I encourage you to think about what documentation changes may have helped steer you _towards_ using WSL and then consider making a PR to improve our docs in that direction.

**Comment by MayaSatishRao** [comment]
@seancolsen Since I was not using WSL, I did see some warnings but the project is working fine on my system. Others might get errors if they do not use WSL. So, I think I will not make any PR's to address Windows based development.

**Comment by seancolsen** [comment]
Ok, thanks for the info @MayaSatishRao. Feel free to report any other issues you experience, especially with other aspects of our development tooling. Since you're not planning on raising a PR, I'm going to close this issue for now. This is a problem that we're already aware of but have chosen to address by instructing devs to use WSL.
