### ISSUE TITLE
impossible to add record when a field appears as not null

### ISSUE THREAD

**Issue by jeromeperez** [mathesar-foundation/mathesar#3400]
## Description
Hi
It's impossible for me to add new record because the primary key of new record is automatically null and i can'modifie it.
I'am an administrator of mathesar.

## Expected behavior
the possibility to modify cell's value to add the record 

## Environment
 - OS: ubuntu 22.04
 - Browser: Firefox 115.7.0esr (64 bits) - Chromium Version 120.0.6099.216 (Build officiel) snap (64 bits)

## Additional context
![mathesar_impossible_add_record](https://github.com/mathesar-foundation/mathesar/assets/22741807/37718caa-9dc5-480c-8f32-d0dc10b78b1c)

**Comment by jeromeperez** [comment]
> @jeromeperez Thank you for reporting this. We'll look into it.
> 
> Could you answer a couple questions:
> 
> * Is the table in the screenshot above created using Mathesar or directly on the database?

the table was created directly in the database

> * Is it correct for me to assume that your PK column does not have a default value set on the database?
> 
It's exact but i tried adding default value and it's the same

> For the Mathesar team, related issues:
> 
For information it's the same with colum not pk but null not allowed or unique with default value

> * [Improve behavior for PK values #1356](https://github.com/mathesar-foundation/mathesar/issues/1356)
> * [Should we allow users to specify PK values while adding records? If so, how? #2336](https://github.com/mathesar-foundation/mathesar/issues/2336)
> * [Allow the front end to add rows to a table with a PK column that has no dynamic default #2124](https://github.com/mathesar-foundation/mathesar/issues/2124)

**Comment by seancolsen** [comment]
I was able to reproduce this as follows.

## Steps to reproduce

### With table rows

1. Create this table outside of Mathesar and [sync external changes](https://docs.mathesar.org/user-guide/syncing-db/).

    ```sql
    create table test_01 (
      name text primary key not null
    );
    ```

2. Load the table page in Mathesar for that table and try to insert a new record.

3. Expect and observe this error:

    ![image](https://github.com/mathesar-foundation/mathesar/assets/42411/616ca17b-2d66-4484-9037-3853114dec78)

    Perhaps the UX could be improve here, but we _do_ expect Mathesar to display an error within the new cell because user input is required before the record can be inserted. This is good.

4. Expect Mathesar to _allow typing into that error cell_.

5. Instead, observe that the cell is disabled — probably because it's a PK cell. _This_ is bad. We need to allow data entry into cells in this state because there is no default value.


### With record selector

We should **also** allow users to create records with the record selector like this:

![image](https://github.com/mathesar-foundation/mathesar/assets/42411/cba2e074-d361-41b8-9959-6c6e263826c8)

We might need to splinter that off into a separate issue if it warrants significantly more implementation effort.

## Status

I'm marking this as ready since we're able to reproduce it now.

I'm restricting this to maintainers since it's important that we consider our previous work on various PK behavior (as @pavish referenced).

## Other scenarios

@jeromeperez you said: 

> For information it's the same with colum not pk but null not allowed or unique with default value

I'm a bit confused about this. Would you be able to provide minimal `CREATE TABLE` statements that can demonstrate the other behavior you seem to be describing?

For example, I tried these tables and was unable to reproduce any similar bugs.

- test_02

    ```sql
    create table test_02 (
      id serial primary key,
      name text not null
    );
    ```

    In this case I'm able to follow my "steps to reproduce" 1 - 4. However, then on step 5 I'm able to type into that error cell. When I press <kbd>Enter</kbd> (or focus away from the cell input) the cell value saves and the record is successfully inserted.

- test_03

    ```sql
    create table test_03 (
      id serial primary key,
      name text unique default ''
    );
    ```

    This is similar to test_02 except that our error feedback does not display in a very helpful way. There are some subtle UX issues we could work on improving here.

    ![image](https://github.com/mathesar-foundation/mathesar/assets/42411/7235ba2e-6839-4ab2-9fb4-3f90ba3ceb21)

    ![image](https://github.com/mathesar-foundation/mathesar/assets/42411/388d31cc-dbf0-403b-b318-07bb6a0bebe3)

    I'm curious if you've run into this situation and perhaps become confused.

    At this point it _is_ possible to type into the "name" cell and submit a new record.

If you could help clarify your experience with situations like the above (and possibly others that I've not yet thought of), that might help us identify other opportunities for improvement!

**Comment by seancolsen** [comment]
Thanks for following up @jeromeperez. You said:

> i became confused when i tried to add value because it was a foreign key and i couldn't add the value because of null primary key in the other table

I'm not sure I understand what you're talking about here but I did try a few things that seemed kind of like what you're describing. I identified one possible problem which does appear to be a bug. Because it's sufficiently separate from the discussion we've already been having in this issue, I opened #3412 to describe that bug in more detail. Is that the situation you're running into? If so, it might be helpful for you to comment on that issue directly and say that you're experiencing that bug. I'd also like to better understand what your use case might be for a foreign key column that references a column which is not a primary key column.

If I've not interpreted your last comment correctly, it would be great if you could post some SQL to help me reproduce the problem without further misunderstandings.

**Comment by jeromeperez** [comment]
> Thanks for following up @jeromeperez. You said:
> 
> > i became confused when i tried to add value because it was a foreign key and i couldn't add the value because of null primary key in the other table
> 
> I'm not sure I understand what you're talking about here but I did try a few things that seemed kind of like what you're describing. I identified one possible problem which does appear to be a bug. Because it's sufficiently separate from the discussion we've already been having in this issue, I opened #3412 to describe that bug in more detail. Is that the situation you're running into? If so, it might be helpful for you to comment on that issue directly and say that you're experiencing that bug. I'd also like to better understand what your use case might be for a foreign key column that references a column which is not a primary key column.
> 
> If I've not interpreted your last comment correctly, it would be great if you could post some SQL to help me reproduce the problem without further misunderstandings.

I solve the problem by modifying table structure adding a serial pk and adding constraint unique to field which was pk before
