### ISSUE TITLE
Make initial loading indication more prominent for table pages

### ISSUE THREAD

**Issue by pavish** [mathesar-foundation/mathesar#3473]
## Problem
* When the table page loads, there's an empty view which gives an impression that there's something wrong with the app.
* The loading indication is at the bottom right and it's not prominent to the user.

https://github.com/mathesar-foundation/mathesar/assets/11850603/bbf6d977-10b1-4436-81fb-93cc44e6a1cb

## Proposed solution
* Present a more prominent loading indication in the center of the page.

**Comment by seancolsen** [comment]
Thanks for reporting this, @pavish. 

- I'm removing `needs: product approval` because I don't imagine that anyone would object to adding a loading indicator.

- I'm removing `needs: ux design` because I think this is something that we can fairly easily improvise.

- Regarding design, I suggest that we add a large loading spinner that appears within the table area, near the top, and horizontally centered.

    As precedent, here are some similar loading spinners that we have:

    - Within the record selector:

        ![image](https://github.com/mathesar-foundation/mathesar/assets/42411/7311dbfc-875e-493a-8fd1-67eca4cb09fa)

    - Within the import preview

        ![image](https://github.com/mathesar-foundation/mathesar/assets/42411/acb55744-e535-41ae-9ab8-93c00ad9f4b0)

    - On the record page:

        ![image](https://github.com/mathesar-foundation/mathesar/assets/42411/67180122-1e2d-4ae4-9989-bf11bf269bfa)

    Notice that we have some inconsistency in the size an color of these loading spinners. It might be nice to fix that by adding a `LargeSpinner` component that we use in cases like this. But I would consider that a very low priority — something that doesn't necessarily need to be done along with adding a loading spinner to the table page.

- To me everything here seems straightforward, and this issue seems worth of moving forward, so I'm marking it as `ready`.

- Because I think this would be fairly easy, I'm also marking it as `help wanted`.
