### ISSUE TITLE
Unable to connect to postgres running on the host's localhost via podman

### ISSUE THREAD

**Issue by wbste** [mathesar-foundation/mathesar#3756]
## Description
Tried to run `podman run -it --name mathesar -p 8000:8000 mathesar/mathesar-prod:latest --network=host`, the application loads the container fine and the web GUI works as intended. However, I cannot connect to a postgres instance running locally on the host machine.

## Expected behavior
Connect to localhost instance

## To Reproduce
Run command above after installing podman. Tried to connect with localhost, host.containers.internal, port 5432

## Environment
 - OS: Windows 11

**Comment by mathemancer** [comment]
1. Do you have other podman containers connecting successfully to that DB?

**Comment by mathemancer** [comment]
> Oh wow, sorry about that. I read the features and it sounded like you could connect to an existing database, and I guess I inferred that meant an externally hosted one.
> 
> _Built on Postgres: Connect to an existing Postgres database or set one up from scratch._
> 
> I find containerizing things that don't need to result in additional overhead. No reason I couldn't containerize it, but I don't know why I would need to. My current database is running as a normal installed application on Windows.
> 
> Let me gather the additional requested information and I'll report back.

You can absolutely connect to an existing database! However, there are security implications specific to connecting from a docker (or podman) container on a machine to a database (or any other service) running on that host machine. These issues are, unfortunately, outside the control of Mathesar (or any service) running within the containerized environment.

If it's essential to connect to a DB running on the host machine, we currently recommend running Mathesar on that host machine rather than in a container.
