### ISSUE TITLE
Make Logo Link Behavior Consistent

### ISSUE THREAD

**Issue by ghislaineguerin** [mathesar-foundation/mathesar#3899]
## Description
When only one database is present, clicking the logo link redirects users directly to that database's page. To manage or connect databases, users must rely on the breadcrumb menu to access the "Manage Databases" option, which is not easy to find.

## Expected behavior
Always redirect to the databases list (or "Home" page) when clicking the logo, regardless of the number of databases available.

## Related

- #3287
- #4048

**Comment by seancolsen** [comment]
Agreed. The behavior you describe is exactly the behavior I wanted when we were designing the home page. However (if I recall correctly) @kgodey wanted to redirect the user "into" the database in order to avoid clicks and to get the user more quickly to the stuff they want. Kriti's concern is the reason for our current behavior. As such, I'm labeling this "needs: product approval" to make it clear that we would need sign off from her before implementing this.

**Comment by ghislaineguerin** [comment]
@seancolsen I do recall that, so not necessarily an implementation problem. But it was a weird UX and it took me a while to figure out what was going on with the logo link.

**Comment by pavish** [comment]
We briefly discussed removing redirection at today's meeting instead of fixing issues stemming from redirection such as https://github.com/mathesar-foundation/mathesar/issues/3903. We might want to introduce redirection again later, for which we'll require a UX discussion.

Moving this issue into the testing-1 milestone.
