### ISSUE TITLE
Change records text filtering to be case insensitive

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#4051]
## Steps to reproduce

1. Use our library sample data.
1. Go to the Publishers table page.
1. Filter by Name equals `Crown` (in title case).
1. Expect and observe one result. Good.
1. Change the filter value from `Crown` to `crown` (in lowercase).
1. Expect to see the same one result.
1. Observe no results. Bad.

**Comment by mathemancer** [comment]
Some notes:
- `Contains` is already case insensitive in the front end
- `Starts with` has a case insensitive version in the back end
- I think we should avoid making filtering into a "fuzzy search" Between this and #4052 , I'm worried that's the direction you're heading with these issues. If we want fuzzy searching of table rows, we should make that its own feature. 
- We could always put a little check box next to the filter name "Starts with" to toggle case sensitivity

**Comment by seancolsen** [comment]
@mathemancer

> `Contains` is already case insensitive in the front end

Ah **ha**! Ok, this is a very good point. I didn't realize that!! I have a new idea now (described below).

> We could always put a little check box next to the filter name "Starts with" to toggle case sensitivity

Yeah, I this would be my ideal solution. But it's actually not that easy on the front end. The filtering UI is pretty heavily abstracted and adding a little check box would mean an entirely different _structure_ for filter conditions. It's possible of course, but not exactly low-hanging-fruit, so not the sort of stuff I'm looking for while polishing things pre-beta.

---

For reference, this is the current behavior:

![image](https://github.com/user-attachments/assets/9590e53d-1782-4649-8baa-244cf86e72ab)

The filtering comparisons are:

- `equals`
- `is empty`
- `is not empty`
- `contains`
- `starts with`

**Here's what I think we should do:**

1. Change the order of the filtering comparisons by moving `contains` to the top. This would make it the default comparison for text types and would address the problem I've observed during user testing.

1. Change the filter comparison names to include text describing their case sensitivity.

The result would bhe the following filtering comparisons:

- `contains (case insensitive)`
- `equals (case sensitive)`
- `is empty`
- `is not empty`
- `starts with (case insensitive)`

How does that sound to you, @mathemancer?

**Comment by Anirudh2112** [comment]
Hello @seancolsen and @mathemancer, I would like to contribute to this

**Comment by mathemancer** [comment]
@seancolsen Agreed on all points. Sounds great to me.

**Comment by mathemancer** [comment]
@Anirudh2112 Go for it, and thank you! Please let us know if you run into trouble. Please be aware, if we don't hear back from you on the issue for awhile, we will have to implement it ourselves due to time constarints.

**Comment by Anirudh2112** [comment]
Thank you @mathemancer. Could you please guide me to the script where I'm supposed to make the necessary changes? I have tried looking in mathesar_ui/components and utils but couldn't find it. Thank you

**Comment by seancolsen** [comment]
@Anirudh2112 I searched the codebase for `starts with` and found this file which looks promising:

`mathesar_ui/src/stores/abstract-types/operations/filtering.ts`

I can't guarantee that's correct though. It's going to be up to you to figure some of this stuff out as best you can.

**Comment by Anirudh2112** [comment]
Thank you @seancolsen

**Comment by sharath-1517** [comment]
I have been exploring on this issue and the comments, I have certain questions on it

- When using `equals` to the `string value` the current operation considers `case sensitivity` and does not return that one row since it starts with 'C' and not 'c' which I believe is correct and can be expected(since we have not mentioned anything about case sensitivity in the filters)? If I'm wrong please let me know. I'm thinking of this because, despite the fact that @seancolsen has started this issue with 
> 6. Expect to see the same one result.

and then following up this conversation @mathemancer has described to consider not having the "fuzzy search" here. So Sean has proposed a certain changes with `case sensitivity`
>contains (case insensitive)
equals (case sensitive)

Has the issue changed from,
> Change the filter value from Crown to crown (in lowercase).
Expect to see the same one result.

to,
>contains (case insensitive)
equals (case sensitive)
is empty
is not empty
starts with (case insensitive)

or do we still have to make sure that the record is returned with case insensitivity when choosing the `equals` option. @seancolsen as you have mentioned the above set of UI change proposals. 
- Wouldn't that be much better _**if we change the UI than returning case insensitive records?**_ (this is just my suggestion, if you have any purpose for this please let me know so I may understand the reason exactly why that cannot be done) 

or 
- what if we can provide them an option/description for case insensitive search in the proposal you have provided? Wouldn't that be helpful for the users to understand better? than returning case insensitive records?

Main question: Do we still have to lookout for the `crown` does not return the record which has `Crown` as title ignoring the case sensitivity?

These are the few questions I have. Thanks for your time!

**Comment by seancolsen** [comment]
@sharath-1517 yes, the issue has changed. I was hoping my [comment](https://github.com/mathesar-foundation/mathesar/issues/4051#issuecomment-2529598964) here would be clear enough, but I can see how it's quite different from the original issue description. For the sake of clarity, I'm closing this issue in favor of #4094, which I've just opened.
