### ISSUE TITLE
Performance testing data generation

### ISSUE THREAD

**Issue by mathemancer** [mathesar-foundation/mathesar#83]
**Problem**

Some of the functionality of Mathesar has performance implications w.r.t. the speed with which responses can be expected from the API.  For example, splitting and merging tables can be slow at large scale.

In order to understand these implications, we need to have sample data of different sizes, some very large.

**Proposed solution**

We should create that data via a script to avoid having to sync it in the repo or store it somewhere.  This could also be included in the example notebook mentioned in #82 so that developers can see the performance of different operations.

**Comment by seancolsen** [comment]
I'm closing this issue because it's very old. While I imagine there may still be some relevant work to be done here, I don't think this ticket is doing us much good in its current form. We can re-open if needed, or we can create separate tickets with clearer and more actionable specs for how to move forward.
