### ISSUE TITLE
Create API localization system

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar#895]
We need a system that allows us to translate text within the API response into different languages. This would only apply to text within the Mathesar source code such as error messages.

Most of the text that users will see will be translated at the UI level, and thus covered by #894

**Comment by mathemancer** [comment]
Is this discussed somewhere?  I'm not convinced translating error messages is a good idea, since it inhibits searching, for solutions and so on.  Are error messages from Python itself ever localized, for example?

**Comment by kgodey** [comment]
@mathemancer It was discussed briefly on Matrix, only in enough detail to lead to this placeholder issue. We did talk about localizing API error messages making it hard to search for solutions, but it seems like we can mitigate that by also displaying the error code (which will remain the same). 

Please note that this only applies to the API, not the rest of the source code (e.g. not the `db` module). Localizing API error messages will allow the frontend to show those error messages to the user.

**Comment by seancolsen** [comment]
@mathemancer Here's the [Matrix discussion](https://matrix.to/#/!xPrzlsyLMNbsMzrcrX:matrix.mathesar.org/$R0cmE1mF4n91cLaLf7p77zYuFw3BcMjPudib6dAqHao?via=matrix.mathesar.org) which inconveniently arose in a non-public channel. I shared some concerns very similar to yours.

At the very least I think we might all agree that translating API error messages is a much lower priority than translating the UI. We could potentially defer the translation of API error messages until after we've given some non-english-speaking users the chance to test a version of the product with a localized UI and report their experience.

**Comment by mathemancer** [comment]
> but it seems like we can mitigate that by also displaying the error code (which will remain the same).

Agreed, but some users will (for example) ask about the error on stack overflow by message, and that won't be found by googling the error code.  We'd just be separating out the knowledge base.  If we want to localize errors, I'd rather have it reported initially localized, but have a non-localized version easily available ("click for something to google" or something), and encourage them to use that when seeking help if they can't find any with the localized version.

Actually, as I think about it, I'd even think there's an advantage to someone asking for help with an english error message on a spanish help forum, since at least then someone could find the thread and google translate it.

I'm not completely dead-set against this, but I'd be interested in whether there are other products at our likely scale that are localizing error messages.

**Comment by seancolsen** [comment]
Closing as a duplicate of #2927
