### ISSUE TITLE
Ensure integrity of columns with foreign key constraints applied

### ISSUE THREAD

**Issue by kgodey** [mathesar-foundation/mathesar#973]
## Problem
Users may try to change the data type of columns with foreign key constraints applied, which may break the foreign key.

## Solution
The API should not allow the data type of a column with a foreign key constraint to be changed.

**Comment by silentninja** [comment]
Is this meant to be a validation step?

**Comment by kgodey** [comment]
> Is this meant to be a validation step?

I'm not sure what you mean.

**Comment by silentninja** [comment]
> > Is this meant to be a validation step?

> I'm not sure what you mean.

If we change the datatype of a foreign key, I think it will cause an error, so I am not sure where this scenario would occur. Will it be a validation we do on the service layer before it gets to the database since the database won't allow this anyway

**Comment by mathemancer** [comment]
> The API should not allow the data type of a column with a foreign key constraint to be changed.

This will be blocked at the DB layer whenever it creates an actual problem (i.e., when it would break the link).  For performance and flexibility, I suggest letting the user make the request, and presenting a "nice" version of the error if it's disallowed by the database.  This would allow, for example, altering the foreign key column and the column it references to a `BIGINT` if there's danger of a rollover in a smooth way that doesn't risk breaking integrity.  Otherwise, you need to drop the constraint, alter each column, then rebuild the constraint.  This introduces the potential for corruption if not handled correctly (i.e., in a single transaction).

**Comment by kgodey** [comment]
@silentninja @mathemancer This is just a requirement from the product side, I did not consider whether the database allowed this or not when creating this ticket. If the DB doesn't allow it, handling this should just be creating the proper exception and error code and showing it in the API.

**Comment by mathemancer** [comment]
@kgodey Would you be okay with altering types whenever it wouldn't break the link?  I.e., when it creates no error at the DB layer?

**Comment by kgodey** [comment]
@mathemancer Yup, that's fine.

**Comment by mathemancer** [comment]
In that case, I suggest just using the default DB behavior and handling errors gracefully.

**Comment by kgodey** [comment]
Closing this, too old, requirements are likely out of date. We can create a new issue if we need this functionality in the future.
